name: Deploy ADF to Dev, RTE, Prod

on:
  push:
    branches:
      - master

permissions:
  id-token: write
  contents: read


jobs:
  deploy-dev:
    runs-on: windows-latest
    steps:
      - name: Checkout adf_publish branch
        uses: actions/checkout@v3
        with:
          ref: adf_publish
          
      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D0D6A26FD0054D38BFAFD083581516A2 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F4914F07D54C49248CF3F2635A6C9EE5 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C873F0E0281F49D89EA0F217F0B99622 }}

      - name: Deploy to Dev
        uses: azure/arm-deploy@v1
        with:
          resourceGroupName: 'ProductImageAppRG'
          template: Christeena/ARMTemplateForFactory.json
          parameters: Christeena/ARMTemplateParametersForFactory.json
          parametersOverrides: >
            factoryName=Christeena
            AzureSqlDatabase1_password=${{ secrets.SQL_PASSWORD }}
            AzureSqlDatabase2_password=${{ secrets.SQL_PASSWORD }}

  deploy-rte:
    runs-on: windows-latest
    needs: deploy-dev
    steps:
      - name: Checkout adf_publish branch
        uses: actions/checkout@v3
        with:
          ref: adf_publish


      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D0D6A26FD0054D38BFAFD083581516A2 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F4914F07D54C49248CF3F2635A6C9EE5 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C873F0E0281F49D89EA0F217F0B99622 }}

      - name: Deploy to RTE
        uses: azure/arm-deploy@v1
        with:
          resourceGroupName: 'ProductImageAppRG'
          template: Christeena/ARMTemplateForFactory.json
          parameters: Christeena/ARMTemplateParametersForFactory.json
          parametersOverrides: >
            factoryName=Christeena
            AzureSqlDatabase1_password=${{ secrets.SQL_PASSWORD }}
            AzureSqlDatabase2_password=${{ secrets.SQL_PASSWORD }}

  deploy-prod:
    runs-on: windows-latest
    needs: deploy-rte
    steps:
      - name: Checkout adf_publish branch
        uses: actions/checkout@v3
        with:
          ref: adf_publish

      - name: Azure Login
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_D0D6A26FD0054D38BFAFD083581516A2 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_F4914F07D54C49248CF3F2635A6C9EE5 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_C873F0E0281F49D89EA0F217F0B99622 }}

      - name: Deploy to Prod
        uses: azure/arm-deploy@v1
        with:
          resourceGroupName: 'ProductImageAppRG'
          template: Christeena/ARMTemplateForFactory.json
          parameters: Christeena/ARMTemplateParametersForFactory.json
          parametersOverrides: >
            factoryName=Christeena
            AzureSqlDatabase1_password=${{ secrets.SQL_PASSWORD }}
            AzureSqlDatabase2_password=${{ secrets.SQL_PASSWORD }}
